### ISSUE TITLE
Source to Arabic Noto fonts

### ISSUE THREAD

**Issue by aiaf** [googlei18n/noto-source#1]
Are they available anywhere?

**Comment by twardoch** [comment]
My understanding is that this repository currently hosts the sources for selected Noto fonts, the ones for which the sources are available in a unified form that is easy to publish and where the build process relies only on open-source tools. The Noto project is huge, and I believe many fonts currently require some custom tools to build. I imagine that the Google i18n team will make more sources available over time. (I'm not in any way affiliated with the team that publishes the Noto fonts, so this is only my opinion based on common understanding.)

**Comment by aiaf** [comment]
I see. Thanks for the insight!

**Comment by dougfelt** [comment]
No current Noto fonts have source published.  The sources in this folder are works in progress for versions of the fonts that have not been released.  The designs or glyph/character repertoires have not been reviewed, basically it's all draft material.

**Comment by behdad** [comment]
> The Noto project is huge, and I believe many fonts currently require some custom tools to build.

We don't even have sources for the previous fonts.  Our contract only included binary drops for those.

**Comment by davelab6** [comment]
I suggest this can be closed
