### ISSUE TITLE
question comparing the pipeline vs glyphs.app outputs

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/noto-source#10]
@jamesgk @dougfelt 

given the state of the https://github.com/googlei18n/noto-source/tree/master/src directory as of 20160714, we (our pipeline) generate the following TTF which glyphs.app does not. Is this intended?
NotoSansHebrew-LightSemiCondensed.ttf
NotoSansHebrew-SemiCondensedRegular.ttf 
NotoSerifArmenian-CondensedRegular.ttf
NotoSerifGeorgian-SemiCondensedRegular.ttf

**Comment by dougfelt** [comment]
I guess we don't use Noto lint at all in testing since it's automatic now.
All of these file names are improperly formed.

**Comment by marekjez86** [comment]
Thanks @dougfelt for the comment. This prompted me to look at when I generated the files. Looks that 2 of them are old (I assume we don't generate them any longer - so this is a user error), but two of them were just built:

-rw-r----- 1 marekj eng 15180 Jun 14 08:02 NotoSansHebrew-LightSemiCondensed.ttf
-rw-r----- 1 marekj eng 15280 Jun 14 08:02 NotoSansHebrew-SemiCondensedRegular.ttf
-rw-r----- 1 marekj eng 17084 Jul 12 07:13 NotoSerifArmenian-CondensedRegular.ttf
-rw-r----- 1 marekj eng 19116 Jul 12 07:50 NotoSerifGeorgian-SemiCondensedRegular.ttf

**Comment by dougfelt** [comment]
I believe our naming says 'Regular' only appears after the hyphen if
nothing else is there.  The same would be true of the internal font names.

**Comment by jamesgk** [comment]
I'm not seeing these files when I run the pipeline. Maybe try updating? (And be sure to run `git submodule update --recursive`.)

**Comment by marekjez86** [comment]
unable to repro
