### ISSUE TITLE
some sources have shortened "familyName", not matching their file name

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/noto-source#107]
All the .glyphs source files (except these two) have their filename matching the respective `familyName` field, minus the spaces (e.g. "Noto Sans" -> "NotoSans-MM.glyphs", "Noto Sans Tamil" -> "NotoSansTamil-MM.glyphs, etc.)

However, for these two, the `familyName` has a shortened form, whereas the file name has the full string:

https://github.com/googlei18n/noto-source/blob/2ceeaa253c82aeae38260d0a4f167a29a659e957/src/NotoSansOldNorthArabian-MM.glyphs#L99

https://github.com/googlei18n/noto-source/blob/a21c6632aa4b4e21a15baf0a64f1dc8a44254e70/src/NotoSansSoraSompeng-MM.glyphs#L106

This creates a problem with the current `build_merged_noto.py` script (the experimental one to make a single merged Noto VF), which assumes that the source file name matches the name of the generated TTF. The latter name (as generated by fontmake) depends on the `familyName`.

Of course, I could make an exception or fix the script to read this field from the actual source file instead of assuming filename and familyName must match.

But since these two are the only exceptions to the general rule, I'd say we should either rename the files to use the compressed name, or rename the familyName to use the full name.

**Comment by anthrotype** [comment]
The "NotoSansOldSouthArabian-MM.glyphs" has the full form, not the compressed one, for the `familyName`:

https://github.com/googlei18n/noto-source/blob/2084ad565405c1a5c26b644c16fc15e860e283e1/src/NotoSansOldSouthArabian-MM.glyphs#L94

for consistency, I'd use the non-compressed name for Old South Arabian, and thus for Sora Sompeng too.

**Comment by anthrotype** [comment]
Hmm... It appears that this was somehow deliberate.
The NotoSansOldNorthArabian-MM.glyphs has a compressed `familyName`

```
familyName = "Noto Sans OldNorArab";
```
but then it has these custom parameters, to use the long form for the preferred family name (nameID 16), the postscript name (nameID 6) and also the file name (but fontmake _does not_ support the latter yet, will open a separate issue). 
```
{
name = preferredFamilyName;
value = "Noto Sans Old North Arabian";
},
{
name = fileName;
value = "NotoSansOldNorthArabian-Regular";
},
{
name = postscriptFontName;
value = "NotoSansOldNorthArabian-Regular";
}
```

On the other hand, the NotoSansOldSouthArabian-MM.glyphs -- as well as all the other Noto sources -- has a _long_ `familyName`:

```
familyName = "Noto Sans Old South Arabian";
```

and has the short form of the name only for use in the nameID 1 (the family name used for style linking in legacy word processors):

```
{
name = styleMapFamilyName;
value = "Noto Sans OldSouArab";
}
```

I believe we should be consistent throughout the Noto sources and use only one of these two approaches. That means the only two exceptions (Old North Arabian and Sora Sompeng) should be modified so that they have

1) the long name in the `familyName`,
2) no `preferredFamilyName` custom parameter (the `familyName` is "preferred"),
3) no `postscriptFontName` (the default familyName-styleName is already correct), 
4) no `fileName` custom parameter (also unneeded, and currently ignored), and
5) a `styleMapFamilyName` custom parameter containing the shortened name.

**Comment by anthrotype** [comment]
correction: we _do_ read the `fileName` custom parameter, but only when generating instances (as it is in fact an instance custom parameter).
When one creates UFO mastes or ttf-interpolatable masters from a glyphs source, the UFO masters (generated by glyphsLib) will have their file name `<familyName>-<styleName>.ufo`, and same for the master TTFs (but with a .ttf extension).

In general, for single-master-single-instance kind of fonts (which is the case for Noto Sans Old North Arabian and others mentioned above), one should always build them as instances (with fontmake `-i` option), even though there is no interpolation going on. This way, the instance custom parameters (e.g. this `fileName` one) will be correctly applied.

**Comment by davelab6** [comment]
I'm not aware of any modern environment with name id 1 length restrictions.
I'm curious who can confirm that's still an issue?

**Comment by marekjez86** [comment]
@dougfelt : doug, you might have the best organizational memory of why we had shortened names (although this one could be a mistake). could you share it?

**Comment by dougfelt** [comment]
Several years ago I was told (by the font team and/or Dave) that some
legacy platforms required that we adhere to the old limits on length for
name id 1.  So we do.

**Comment by anthrotype** [comment]
ok, but my question was not whether we should shorten (which I assumed we should for legacy reasons), but rather how to implement the shortening in the glyphs source files.

The two Old North Arabian and Sora Sompeng fonts are the exception to the rule, for the reasons I described above.

**Comment by marekjez86** [comment]
I never looked at it before but
https://github.com/googlei18n/nototools/blob/master/nototools/noto_names.py
might be what you are looking for

**Comment by brawer** [comment]
Curious: Instead of fixing things at the end, why don’t we simply clean up the sources?

**Comment by dougfelt** [comment]
Who's talking about fixing things at the end?

**Comment by anthrotype** [comment]
exactly, i'm proposing to fix up the two sources that are at odds with the rest, to make their familyName match their filename, and to use styleMapFamilyName for the shortened name.

**Comment by davelab6** [comment]
Looks like Font Bakery checks for family name being 31 chars or less.

https://github.com/googlefonts/fontbakery/blob/fc9a4e68e5f002fe5df805b5fc6696b6bd1732cd/Lib/fontbakery/specifications/googlefonts.py#L2763

Seems fixing the sources are Cosimo proposes will conform to that :)

**Comment by anthrotype** [comment]
it looks like the NotoSansCanadianAboriginal-MM.glyphs file added a few days ago with https://github.com/googlei18n/noto-source/commit/d1151ec79750e4bc68a63d68bec6ed509fd56389 also has the same issue as the one reported here.

the font's familyName is set to the compressed form "Noto Sans CanAborig", not matching the source filename. And it uses the `preferredFamilyName` custom parameter for the full name "Noto Sans Canadian Aboriginal".

We should apply the same changes as #109 and perhaps tell the vendor to do the same for all the following deliveries.

/cc @marekjez86
