### ISSUE TITLE
NotoNastaliqUrdu: why neither "Sans" nor "Serif"?

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/noto-source#116]
Sorry, I'm not an Arabic font expert. I just wondering why "Noto Nastaliq Urdu" is the only source file that doesn't fit in the Sans vs Serif classification. All the rest of the Noto fonts are either one or the other.

From a more practical point of view, if one wished to make two big NotoSans and NotoSerif fonts that include all the scripts, in which of the two would this Nastaliq Urdu be included? Both?

**Comment by khaledhosny** [comment]
There is also Noto Naskh Arabic and Noto Kufi Arabic. Basically, the sans
and serif classification is a LGC thing and does not fit into Arabic, at
least not the traditional styles like Naskh and Nastaliq.

**Comment by anthrotype** [comment]
I see, thanks. I only noticed the Nastaliq because there are no source files in here yet for the Naskh and Kufi you mentioned.

So your answer to my question whether Nastaliq Urdu should be included in the merged Noto Sans or Noto Serif or both, is basically "neither". That is, it's something else, beyond the classification.

**Comment by khaledhosny** [comment]
Yes, I think it should remain a standalone font.

**Comment by marekjez86** [comment]
@anthrotype : I think @khaledhosny answered the question. Please reopen you you need more info
