### ISSUE TITLE
Add Egyptian Hieroglyphs support

### ISSUE THREAD

**Issue by pamputt** [googlei18n/noto-source#19]
I installed all Google Noto Fonts and Firefox still does not support the display of Egyptian hieroglyphs. See for example https://en.wikipedia.org/wiki/Egyptian_Hieroglyphs_%28Unicode_block%29

**Comment by pamputt** [comment]
Actually the problem of display only happens on Firefox. Characters are correctly displayed with Chromium 53. SOrry for the noise.

**Comment by marekjez86** [comment]
The problem is with the rendering engine in Firefox.
