### ISSUE TITLE
 Add full support of Linear B

### ISSUE THREAD

**Issue by pamputt** [googlei18n/noto-source#20]
I installed all Google Noto Fonts and Firefox still does not support the display of Linear B script. See for example https://en.wikipedia.org/wiki/Linear_B

**Comment by dougfelt** [comment]
The Linear B should be part of the package.  What platform are you running on?  Have you tried Chrome on it, does it have the same issue?

**Comment by pamputt** [comment]
Oh! Indeed, the problem of display happens only on Firefox. It works perfectly on Chromium 53. Sorry for the noise. I hope it is not the same for all the others tickets I opened

**Comment by dougfelt** [comment]
Can you check the others?  We should still investigate the issue on Firefox but it may be we should consolidate the tickets into one.

I'm also assuming that you are only testing the scripts for fonts currently in the package.  Some scripts are not available yet (in particular, scripts that appeared after Unicode 6 are still forthcoming).

**Comment by dougfelt** [comment]
@jungshik, are you aware of any issues with Firefox and the fonts @pamputt has mentioned in these recent issues?

**Comment by pamputt** [comment]
A bug report has been opened on Firefox bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1309700

**Comment by marekjez86** [comment]
We currently plan to provide an update to Linear B and Linear A scripts between next year and 2019. Please stay tuned.
