### ISSUE TITLE
Add Kharoshthi support

### ISSUE THREAD

**Issue by pamputt** [googlei18n/noto-source#21]
I installed all Google Noto Fonts and Firefox still does not support the display of Kharoshthi. See for example https://en.wikipedia.org/wiki/Kharoshthi_%28Unicode_block%29

**Comment by marekjez86** [comment]
We currently plan to support Kharoshthi script between next year and 2019. Please stay tuned.

**Comment by behdad** [comment]
Humm.  We have NotoSansKharoshti in https://github.com/googlei18n/noto-fonts/tree/master/unhinted
Sure, it's not in noto-source yet.
