### ISSUE TITLE
Add Lydian support

### ISSUE THREAD

**Issue by pamputt** [googlei18n/noto-source#22]
I installed all Google Noto Fonts and Firefox still does not support the display of Lydian. See for example https://en.wikipedia.org/wiki/Lydian_%28Unicode_block%29

**Comment by pamputt** [comment]
Actually the problem of display only happens on Firefox. Characters are correctly displayed with Chromium 53

**Comment by marekjez86** [comment]
The problem is with Firefox rendering engine. Closing the issue.
