### ISSUE TITLE
Add support for Anatolian Hieroglyphs

### ISSUE THREAD

**Issue by pamputt** [googlei18n/noto-source#23]
I installed all Google Noto Fonts and Firefox still does not support the display of Anatolian Hieroglyphs. See for example https://en.wikipedia.org/wiki/Anatolian_Hieroglyphs_%28Unicode_block%29

**Comment by marekjez86** [comment]
We currently plan to support Anatolian Hieroglyphs script between next year and 2019. Please stay tuned.
