### ISSUE TITLE
Add support for Meroitic

### ISSUE THREAD

**Issue by pamputt** [googlei18n/noto-source#24]
I installed all Google Noto Fonts and Firefox still does not support the display of Meroitic. See for example https://en.wikipedia.org/wiki/Meroitic_Cursive_%28Unicode_block%29 and https://en.wikipedia.org/wiki/Meroitic_Hieroglyphs_%28Unicode_block%29

**Comment by marekjez86** [comment]
We currently plan to support Meroitic Cursive and Meroitic Hieroglyphs scripts between next year and 2019. Please stay tuned.
