### ISSUE TITLE
Add support for Pahlavi

### ISSUE THREAD

**Issue by pamputt** [googlei18n/noto-source#26]
I installed all Google Noto Fonts and Firefox still does not support the display of Pahlavi. See for example https://en.wikipedia.org/wiki/Psalter_Pahlavi_%28Unicode_block%29 , https://en.wikipedia.org/wiki/Inscriptional_Pahlavi_%28Unicode_block%29 and https://en.wikipedia.org/wiki/Inscriptional_Parthian_%28Unicode_block%29

**Comment by marekjez86** [comment]
We currently plan to support Inscriptional Pahlavi and Psalter Pahlavi (I'm not certain which one you had in mind) between next year and 2019. Please stay tuned.
