### ISSUE TITLE
Strip certain variations in a variable font

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/noto-source#29]
A full Noto variable font that has 4 masters in weight variation and 2 masters in width variation can be large. 

It'll be great if fontmake supports striping certain variations, e.g., the condensed width variation, and/or a master in the weight variation to reduce the size of a variable font. 

@jamesgk @brawer @behdad

**Comment by behdad** [comment]
This definitely will be possible down the road (by cropping variation space; not by discarding listed masters), but IMO this is rather low priority.  Definitely not this quarter..

**Comment by jamesgk** [comment]
Duplicate of https://github.com/googlei18n/fontmake/issues/173
