### ISSUE TITLE
License of Glyphdata.xml in this repp

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/noto-source#3]
I just found out that this Repo hosts a GlyphData.xml file under the Apache license. The file contains content from the file from within Glyphs. I did not agree to that. So the file has to be removed and a solution has to be found. I’m open to this. 

For some time, Glyphs can store the relevant data (production name, category, script) in the file. That makes the file independent from the GlyphsData file.

**Comment by davelab6** [comment]
https://rtyley.github.io/bfg-repo-cleaner/ might be helpful

**Comment by schriftgestalt** [comment]
As a first step to resolve that problem. What infos in the file you need?

**Comment by jamesgk** [comment]
I don't think we need the file in this repo. So it's sufficient to remove it from the revision history?

**Comment by jamesgk** [comment]
Hmm. I went ahead and tried to do this, but there's still the issue of forks, and the pull request which refers to outdated commits. There's only three forks, so maybe we can just ask the owners to pull the latest upstream and push. We may be able to ask GitHub support to remove the PR.

**Comment by davelab6** [comment]
I've deleted my fork. If @anthrotype deletes his fork and you email
support@github.com to remove the PR I think we are good.

On 8 February 2016 at 18:57, James Godfrey-Kittle <notifications@github.com>
wrote:

> Hmm. I went ahead and tried to do this, but there's still the issue of
> forks, and the pull request which refers to outdated commits. There's only
> three forks, so maybe we can just ask the owners to pull the latest
> upstream and push. We may be able to ask GitHub support to remove the PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/noto-source/issues/3#issuecomment-181630871>
> .
>



-- 
Cheers
Dave

**Comment by behdad** [comment]
Our preference indeed that the .glyphs file has all the necessary data to build the fonts.

The question now is, if we want to edit the sources in Glyphs, do we need the custom Glyphdata.xml?  We probably first need to diff this version to Georg's and see what changes Monotype made.

**Comment by twardoch** [comment]
My understanding is that the file is not needed for the build process as long as the development glyph names are stored in the .glyphs files. @schriftgestalt could you remind us how tomake sure that the mapping of development to final glyph names is stored in the .glyphs file? Some custom parameter or option?

**Comment by schriftgestalt** [comment]
To store the production name in the file, select the glyph in the font view and hit cmd+opt+I. Set the checkbox next to Production Name. That should work for multiple selected glyphs.

**Comment by anthrotype** [comment]
I've just deleted my fork.

**Comment by davelab6** [comment]
https://github.com/googlei18n/noto-source/network shows no more forks, so I think this can now be closed

**Comment by twardoch** [comment]
@jamesgk: @schriftgestalt has just published a subset of GlyphData.xml (just the basic stuff i.e. Unicode-to-Glyphs-glyphname mapping and some categorization, without the additional metadata) under the MIT license: 
https://github.com/schriftgestalt/GlyphsInfo
