### ISSUE TITLE
NotoSansEthiopic-MM-20160908.glyphs and NotoSansEthiopic-MM.glyphs

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/noto-source#31]
what's the difference? should we remove NotoSansEthiopic-MM-20160908.glyphs?

**Comment by marekjez86** [comment]
NotoSansEthiopic-MM-20160908.glyphs was used for testing pipeline (it crashed for a while). Pipeline is fixed. We'll get a new version of NotoSansEthiopic-MM.glyphs. NotoSansEthiopic-MM-20160908.glyphs is not needed.
