### ISSUE TITLE
Weight values of MM fonts

### ISSUE THREAD

**Issue by simoncozens** [googlei18n/noto-source#32]
Noto Sans Khmer has a weight axis in the fvar table ranging from 26 to 190 with a default value of 90.

The OT spec says that for the wght axis, "Values must be in the range 1 to 1000. Values can be interpreted in direct comparison to values for usWeightClass (in the 'OS/2' table), or the CSS font-weight property."

Peter Constable says "That's a font with width ranging from super-extra-thin to extra-extra-light."

**Comment by behdad** [comment]
Yeah I have to fix that...

**Comment by brawer** [comment]
@simoncozens, thanks for the report. Closing this bug because it’s actually not a problem with the font sources; they already contain the needed information. Instead, we have a problem with the build pipeline; see https://github.com/googlei18n/fontmake/issues/167 for details.
