### ISSUE TITLE
Developing a font-based software framework

### ISSUE THREAD

**Issue by gmcarlson518** [googlei18n/noto-source#78]
I want to implement the Noto font system directly into a software framework I'm working on. I read to "...get in touch with us first through the issue tracker with your idea..." so I hope I'm submitting the right thing in the right place.

The first thing I want to do with my software framework is implement a new character encoding API that represents ascii characters using font-type data instead of utf8 standard encoding, removing the utf8 middle man. For this, I decided to use the most unifying font type system in the world, Noto. I have a blank SDL2 window ready to start prototyping my framework with, so my next step is to reverse engineer the Noto schematic. Do you have any pointers for me?

**Comment by davelab6** [comment]
As I understand it, ASCII and ut 8 are identical. No?

**Comment by gmcarlson518** [comment]
More or less. I thought ascii was specific to visual characters that get drawn, vs. "bell" or "del", but perhaps that's a semantic interpretation I got from the term "ascii art." Anyway, utf8/ascii are the "middle man" I was hoping to omit from my framework. I was wondering if I could get some pointers on how Noto character data represents lines, curves and connecting points and what-not that define the shape of characters; to reverse engineer the character data.

**Comment by dougfelt** [comment]
What do you mean by 'character encoding system'?  That's what UTF-8 is.  You mean you want to just draw glyphs?  That's not the same as text, so I guess you don't want to render text?

You can use freetype or cairo to render individual glyphs into bitmaps or outlines.

**Comment by gmcarlson518** [comment]
I'm making a character encoding system, other than utf8, that's based on the shape of the characters themselves, rather than being assigned an arbitrary numeric value that has to be standardized; as for utf8.

So for that, I think what I really need is a data base that identifies individual symbols and the mathematical qualities of their curves, rather than an artistic glyph rendering repository. Then I could base my encoding system off of that database. 

 Do you know of any databases that identify symbols and their curve properties?

**Comment by dougfelt** [comment]
So ASCII seems doable since there's no shaping, reordering, or required combining behavior to deal with, and it's a small set.  Other scripts would be harder to use this approach with.  There are shape-based input methods for CJK which sounds a bit similar, CJK doesn't shape either and the large repertoire drives a desire to use a shape-based approach.

As I said you could use freetype or cairo to render the glyph outlines, and then analyze that as you find sufficient for your purposes. You could also use fontTools and create 'pen' objects for a glyph to examine its outline. I don't know of any glyph-shape-based database for ASCII.

**Comment by gmcarlson518** [comment]
Okay. I'll look into cjk and see what they're about and look around for other resources. Thanks for your time.

**Comment by gmcarlson518** [comment]
So here's a question. When you develope fonts, do you have references that tell you the rules on how to draw those symbols by hand? For example, on that article about noto fonts, they talked about how researchers were designing a font for the monks language. They asked the monks to critique their work, and they wrote notes on the paper such as "the curve goes under the neck, not above" and things like that.

Do you have references like that to guide how fonts are designed?

**Comment by davelab6** [comment]
The font designs are the references 😂

**Comment by gmcarlson518** [comment]
That's not quite what I had in mind 😑 Well, I guess that was my first thought because I turned to a font project. Thanks again for your time.
