### ISSUE TITLE
Pipeline-generated Noto Arabic Sans has bad GDEF

### ISSUE THREAD

**Issue by behdad** [googlei18n/noto-source#83]
I see U+654 HAMZA ABOVE taking non-zero advance with hb-view, which suggests that it has wrong GDEF class (class 1 instead of 3).  Haven't checked more closely.  Filing to debug later.

**Comment by anthrotype** [comment]
yes, I confirm the glyph "hamzaabove-ar" (which is mapped to unicode 0654) is being assigned a GDEF GlyphClassDef 3 ("Marks") by glyphsLib, which means it's advance width is also automatically zeroed by glyphsLib, following Glyphs.app export-time behaviour for mark glyphs.

is @behdad is suggesting that the glyph should instead be categorised as Base glyph (class 1), and hence not have its advance zeroed?

This is what the `glyphdata.get_glyph` function returns for that glyph name:

```python
>>> from glyphsLib.glyphdata import get_glyph
>>> get_glyph("hamzaabove-ar")
Glyph(name='hamzaabove-ar', production_name='uni0654', unicode='ٔ', category='Mark', subCategory='Nonspacing')
```

The "hamzaabove-ar" glyph name is mapped to "uni0654" production name in the GlyphData.xml (as encoded in the glyphdata_generated.py file).
We then use that unicode string ("\u0654") to look up its `unicodedata.category`, and the result is category "Mn" which means "Mark Nonspacing".
http://www.fileformat.info/info/unicode/category/Mn/list.htm

**Comment by behdad** [comment]
No, I agree it should be class 3. I thought we generate it wrong though.

**Comment by behdad** [comment]
I cannot reproduce.
