### ISSUE TITLE
build crashed at line 21 of util.sh

### ISSUE THREAD

**Issue by themaddoctor** [googlei18n/noto-source#96]
After about 5 hours, the build of noto ended with "killed [some number] at line 21 of util.sh" (I am paraphrasing because I closed the terminal; but it was definitely line 21 of util.sh).

In those 5 hours, it went through about 20 different weights and generated glyphs.
It got almost to "ExtraCondensed" in generating UFOs when it crashed.

I am running it again, to see if the result is any different.

**Comment by themaddoctor** [comment]
noto-source-master > ./build all
==== building src/NotoSans-ItalicMM.glyphs ====
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSans-LightItalic.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSans-RegularItalic.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSans-SemiBoldItalic.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSans-BoldItalic.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSans-CondensedLightItalic.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSans-CondensedRegularItalic.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSans-CondensedSemiBoldItalic.ufo
INFO:glyphsLib.util:Writing master_ufo/NotoSans-CondensedBoldItalic.ufo
INFO:fontmake.font_project:Interpolating master UFOs from designspace
INFO:mutatorMath:Reading master_ufo/NotoSans-Italic.designspace
INFO:mutatorMath:       Generating instance NotoSans-ThinItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-ExtraLightItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-LightItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-Italic.ufo
INFO:mutatorMath:       Generating instance NotoSans-MediumItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-SemiBoldItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-BoldItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-ExtraBoldItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-BlackItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-SemiCondensedThinItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-SemiCondensedExtraLightItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-SemiCondensedLightItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-SemiCondensedItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-SemiCondensedMediumItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-SemiCondensedSemiBoldItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-SemiCondensedBoldItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-SemiCondensedExtraBoldItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-SemiCondensedBlackItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-CondensedThinItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-CondensedExtraLightItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-CondensedLightItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-CondensedItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-CondensedMediumItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-CondensedSemiBoldItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-CondensedBoldItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-CondensedExtraBoldItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-CondensedBlackItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-ExtraCondensedThinItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-ExtraCondensedExtraLightItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-ExtraCondensedLightItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-ExtraCondensedItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-ExtraCondensedMediumItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-ExtraCondensedSemiBoldItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-ExtraCondensedBoldItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-ExtraCondensedExtraBoldItalic.ufo
INFO:mutatorMath:       Generating instance NotoSans-ExtraCondensedBlackItalic.ufo
INFO:fontmake.font_project:Building OTFs
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-ThinItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-ExtraLightItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-LightItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-Italic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-MediumItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-SemiBoldItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-BoldItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-ExtraBoldItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-BlackItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-SemiCondensedThinItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-SemiCondensedExtraLightItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-SemiCondensedLightItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-SemiCondensedItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-SemiCondensedMediumItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-SemiCondensedSemiBoldItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-SemiCondensedBoldItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-SemiCondensedExtraBoldItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-SemiCondensedBlackItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-CondensedThinItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-CondensedExtraLightItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-CondensedLightItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-CondensedItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-CondensedMediumItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-CondensedSemiBoldItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-CondensedBoldItalic
INFO:fontmake.font_project:Decomposing glyphs for NotoSans-CondensedExtraBoldItalic
util.sh: line 21:  7685 Killed                  fontmake -g "$1" -o "${@:2}" -i

**Comment by themaddoctor** [comment]
Also, the behavior is verrryy different, depending on whether I SSH into the machine or use a local terminal. On a local terminal, it builds one ttf to completion before moving on to another. "env | grep -i py" shows nothing, so I think both cases use the same python (2.7).

**Comment by anthrotype** [comment]
you may have run out of RAM, sorry...
Try to build one at a time and see if you get to the end.

**Comment by themaddoctor** [comment]
How can I invoke the "build" script to make only one at a time? TY

**Comment by anthrotype** [comment]
Look in the README under Building section, it should explain how to build single font family.

**Comment by anthrotype** [comment]
Note that some Noto families are in a subfolder of their own inside src; in these cases, the main entry point to be given as argument to the `./build` script is not the *.glyphs file, but the *.plist file with the same name.

For example, to build Noto Sans Adlam, you don't do `./build src/NotoSansAdlam/NotoSansAdlam-MM.glyphs`, but you do instead `./build src/NotoSansAdlam/NotoSansAdlam-MM.plist`.
If you pass the *.glyphs file instead of the *.plist one, the generated fonts will not contain OpenType features.

The source of the OT features for some Noto families is stored as MTI format (as specified in those plist files), instead of the usual Adobe Feature File (*.fea) format (embedded in the *.glyphs file).

**Comment by themaddoctor** [comment]
Thank you. Will try that soon. I gave the machine an additional 8GB, but
memory is full again, and the Sans Italics aren't even finished.


On 10/22/17, Cosimo Lupo <notifications@github.com> wrote:
> Note that some Noto families are in a subfolder of their own inside src; in
> these cases, the main entry point to be given as argument to the `./build`
> script is not the *.glyphs file, but the *.plist file with the same name.
>
> For example, to build Noto Sans Adlam, you don't do `./build
> src/NotoSansAdlam/NotoSansAdlam-MM.glyphs`, but you do instead `./build
> src/NotoSansAdlam/NotoSansAdlam-MM.plist`.
> If you pass the *.glyphs file instead of the *.plist one, the generated
> fonts will not contain OpenType features.
>
> The source of the OT features for some Noto families is stored as MTI format
> (as specified in those plist files), instead of the usual Adobe Feature File
> (*.fea) format (embedded in the *.glyphs file).
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/googlei18n/noto-source/issues/96#issuecomment-338465959


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F

**Comment by themaddoctor** [comment]
Seriously, though. I gave the machine 12GB of RAM and swap to use, and it couldn't finish the italics TTFs. This project needs a warning label.

WARNING: YOU NEED AT LEAST __GB OF FREE RAM TO BUILD THIS PROJECT

I don't even know what to put in the blank.

**Comment by anthrotype** [comment]
Which fonts are trying to build and what command did you use?

**Comment by themaddoctor** [comment]
All of them.
./build all

**Comment by themaddoctor** [comment]
I stopped the build because it was thrashing my swap file for four days, and only about 1/4 of the fonts were finished. The max mem+swap that I noticed it using was 13½GB. So... looks like the min RAM requirement for this project is 16GB.
